var f;
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function ca(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ea(a,b){null!=a&&this.append.apply(this,arguments)}ea.prototype.pa="";ea.prototype.append=function(a,b,c){this.pa+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.pa+=arguments[d];return this};ea.prototype.toString=function(){return this.pa};var fa=null;function ha(){return new ia(null,5,[ja,!0,ka,!0,la,!1,ma,!1,na,null],null)}function q(a){return null!=a&&!1!==a}function oa(a){return q(a)?!1:!0}function s(a,b){return a[m(null==b?null:b)]?!0:a._?!0:t?!1:null}function pa(a){return null==a?null:a.constructor}function v(a,b){var c=pa(b),c=q(q(c)?c.mb:c)?c.lb:m(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function qa(a){var b=a.lb;return q(b)?b:""+w(a)}
function x(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}var ra={},sa={};function y(a){if(a?a.F:a)return a.F(a);var b;b=y[m(null==a?null:a)];if(!b&&(b=y._,!b))throw v("ICounted.-count",a);return b.call(null,a)}function ta(a,b){if(a?a.B:a)return a.B(a,b);var c;c=ta[m(null==a?null:a)];if(!c&&(c=ta._,!c))throw v("ICollection.-conj",a);return c.call(null,a,b)}
var ua={},z=function(){function a(a,b,c){if(a?a.S:a)return a.S(a,b,c);var h;h=z[m(null==a?null:a)];if(!h&&(h=z._,!h))throw v("IIndexed.-nth",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.K:a)return a.K(a,b);var c;c=z[m(null==a?null:a)];if(!c&&(c=z._,!c))throw v("IIndexed.-nth",a);return c.call(null,a,b)}var c=null,c=function(d,c,g){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),
va={};function A(a){if(a?a.P:a)return a.P(a);var b;b=A[m(null==a?null:a)];if(!b&&(b=A._,!b))throw v("ISeq.-first",a);return b.call(null,a)}function B(a){if(a?a.Q:a)return a.Q(a);var b;b=B[m(null==a?null:a)];if(!b&&(b=B._,!b))throw v("ISeq.-rest",a);return b.call(null,a)}
var wa={},C=function(){function a(a,b,c){if(a?a.M:a)return a.M(a,b,c);var h;h=C[m(null==a?null:a)];if(!h&&(h=C._,!h))throw v("ILookup.-lookup",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.L:a)return a.L(a,b);var c;c=C[m(null==a?null:a)];if(!c&&(c=C._,!c))throw v("ILookup.-lookup",a);return c.call(null,a,b)}var c=null,c=function(d,c,g){switch(arguments.length){case 2:return b.call(this,d,c);case 3:return a.call(this,d,c,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function xa(a,b,c){if(a?a.qa:a)return a.qa(a,b,c);var d;d=xa[m(null==a?null:a)];if(!d&&(d=xa._,!d))throw v("IAssociative.-assoc",a);return d.call(null,a,b,c)}var za={},Aa={};function Ba(a){if(a?a.Ua:a)return a.Ua();var b;b=Ba[m(null==a?null:a)];if(!b&&(b=Ba._,!b))throw v("IMapEntry.-key",a);return b.call(null,a)}function Ca(a){if(a?a.Va:a)return a.Va();var b;b=Ca[m(null==a?null:a)];if(!b&&(b=Ca._,!b))throw v("IMapEntry.-val",a);return b.call(null,a)}var Da={};
function Ea(a,b,c){if(a?a.Qa:a)return a.Qa(a,b,c);var d;d=Ea[m(null==a?null:a)];if(!d&&(d=Ea._,!d))throw v("IVector.-assoc-n",a);return d.call(null,a,b,c)}function F(a){if(a?a.ab:a)return a.state;var b;b=F[m(null==a?null:a)];if(!b&&(b=F._,!b))throw v("IDeref.-deref",a);return b.call(null,a)}var Fa={};function Ga(a){if(a?a.G:a)return a.G(a);var b;b=Ga[m(null==a?null:a)];if(!b&&(b=Ga._,!b))throw v("IMeta.-meta",a);return b.call(null,a)}
function Ha(a,b){if(a?a.I:a)return a.I(a,b);var c;c=Ha[m(null==a?null:a)];if(!c&&(c=Ha._,!c))throw v("IWithMeta.-with-meta",a);return c.call(null,a,b)}
var Ia={},Ja=function(){function a(a,b,c){if(a?a.O:a)return a.O(a,b,c);var h;h=Ja[m(null==a?null:a)];if(!h&&(h=Ja._,!h))throw v("IReduce.-reduce",a);return h.call(null,a,b,c)}function b(a,b){if(a?a.N:a)return a.N(a,b);var c;c=Ja[m(null==a?null:a)];if(!c&&(c=Ja._,!c))throw v("IReduce.-reduce",a);return c.call(null,a,b)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();
function Ka(a,b){if(a?a.t:a)return a.t(a,b);var c;c=Ka[m(null==a?null:a)];if(!c&&(c=Ka._,!c))throw v("IEquiv.-equiv",a);return c.call(null,a,b)}function La(a){if(a?a.w:a)return a.w(a);var b;b=La[m(null==a?null:a)];if(!b&&(b=La._,!b))throw v("IHash.-hash",a);return b.call(null,a)}var Ma={};function Na(a){if(a?a.C:a)return a.C(a);var b;b=Na[m(null==a?null:a)];if(!b&&(b=Na._,!b))throw v("ISeqable.-seq",a);return b.call(null,a)}var Oa={};
function G(a,b){if(a?a.Ya:a)return a.Ya(0,b);var c;c=G[m(null==a?null:a)];if(!c&&(c=G._,!c))throw v("IWriter.-write",a);return c.call(null,a,b)}var Pa={};function Qa(a,b,c){if(a?a.u:a)return a.u(a,b,c);var d;d=Qa[m(null==a?null:a)];if(!d&&(d=Qa._,!d))throw v("IPrintWithWriter.-pr-writer",a);return d.call(null,a,b,c)}function Ra(a,b,c){if(a?a.Xa:a)return a.Xa(0,b,c);var d;d=Ra[m(null==a?null:a)];if(!d&&(d=Ra._,!d))throw v("IWatchable.-notify-watches",a);return d.call(null,a,b,c)}
function Sa(a){if(a?a.ra:a)return a.ra(a);var b;b=Sa[m(null==a?null:a)];if(!b&&(b=Sa._,!b))throw v("IEditableCollection.-as-transient",a);return b.call(null,a)}function Ta(a,b){if(a?a.xa:a)return a.xa(a,b);var c;c=Ta[m(null==a?null:a)];if(!c&&(c=Ta._,!c))throw v("ITransientCollection.-conj!",a);return c.call(null,a,b)}function Ua(a){if(a?a.ya:a)return a.ya(a);var b;b=Ua[m(null==a?null:a)];if(!b&&(b=Ua._,!b))throw v("ITransientCollection.-persistent!",a);return b.call(null,a)}
function Va(a,b,c){if(a?a.ta:a)return a.ta(a,b,c);var d;d=Va[m(null==a?null:a)];if(!d&&(d=Va._,!d))throw v("ITransientAssociative.-assoc!",a);return d.call(null,a,b,c)}function Wa(a,b,c){if(a?a.Wa:a)return a.Wa(0,b,c);var d;d=Wa[m(null==a?null:a)];if(!d&&(d=Wa._,!d))throw v("ITransientVector.-assoc-n!",a);return d.call(null,a,b,c)}function Xa(a){if(a?a.Ra:a)return a.Ra();var b;b=Xa[m(null==a?null:a)];if(!b&&(b=Xa._,!b))throw v("IChunk.-drop-first",a);return b.call(null,a)}
function Ya(a){if(a?a.Ba:a)return a.Ba(a);var b;b=Ya[m(null==a?null:a)];if(!b&&(b=Ya._,!b))throw v("IChunkedSeq.-chunked-first",a);return b.call(null,a)}function Za(a){if(a?a.Ca:a)return a.Ca(a);var b;b=Za[m(null==a?null:a)];if(!b&&(b=Za._,!b))throw v("IChunkedSeq.-chunked-rest",a);return b.call(null,a)}function $a(a){if(a?a.Aa:a)return a.Aa(a);var b;b=$a[m(null==a?null:a)];if(!b&&(b=$a._,!b))throw v("IChunkedNext.-chunked-next",a);return b.call(null,a)}
function ab(a){this.nb=a;this.o=0;this.f=1073741824}ab.prototype.Ya=function(a,b){return this.nb.append(b)};function H(a){var b=new ea;a.u(null,new ab(b),ha());return""+w(b)}function bb(a,b){if(q(cb.a?cb.a(a,b):cb.call(null,a,b)))return 0;var c=oa(a.J);if(q(c?b.J:c))return-1;if(q(a.J)){if(oa(b.J))return 1;c=db.a?db.a(a.J,b.J):db.call(null,a.J,b.J);return 0===c?db.a?db.a(a.name,b.name):db.call(null,a.name,b.name):c}return eb?db.a?db.a(a.name,b.name):db.call(null,a.name,b.name):null}
function fb(a,b,c,d,e){this.J=a;this.name=b;this.ga=c;this.ha=d;this.oa=e;this.f=2154168321;this.o=4096}f=fb.prototype;f.u=function(a,b){return G(b,this.ga)};f.w=function(){var a=this.ha;return null!=a?a:this.ha=a=gb.a?gb.a(I.d?I.d(this.J):I.call(null,this.J),I.d?I.d(this.name):I.call(null,this.name)):gb.call(null,I.d?I.d(this.J):I.call(null,this.J),I.d?I.d(this.name):I.call(null,this.name))};f.I=function(a,b){return new fb(this.J,this.name,this.ga,this.ha,b)};f.G=function(){return this.oa};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return C.c(c,this,null);case 3:return C.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return C.c(a,this,null)};f.a=function(a,b){return C.c(a,this,b)};f.t=function(a,b){return b instanceof fb?this.ga===b.ga:!1};f.toString=function(){return this.ga};
function J(a){if(null==a)return null;if(a&&(a.f&8388608||a.vb))return a.C(null);if(a instanceof Array||"string"===typeof a)return 0===a.length?null:new hb(a,0);if(s(Ma,a))return Na(a);if(t)throw Error([w(a),w("is not ISeqable")].join(""));return null}function L(a){if(null==a)return null;if(a&&(a.f&64||a.sa))return a.P(null);a=J(a);return null==a?null:A(a)}function M(a){return null!=a?a&&(a.f&64||a.sa)?a.Q(null):(a=J(a))?B(a):N:N}
function P(a){return null==a?null:a&&(a.f&128||a.ub)?a.Z(null):J(M(a))}
var cb=function(){function a(a,b){return null==a?null==b:a===b||Ka(a,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(b.a(a,d))if(P(e))a=d,d=L(e),e=P(e);else return b.a(d,L(e));else return!1}a.m=2;a.h=function(a){var b=L(a);a=P(a);var d=L(a);a=M(a);return c(b,d,a)};a.g=c;return a}(),b=function(b,e,g){switch(arguments.length){case 1:return!0;case 2:return a.call(this,b,
e);default:return c.g(b,e,Q(arguments,2))}throw Error("Invalid arity: "+arguments.length);};b.m=2;b.h=c.h;b.d=function(){return!0};b.a=a;b.g=c.g;return b}();sa["null"]=!0;y["null"]=function(){return 0};Date.prototype.t=function(a,b){return b instanceof Date&&this.toString()===b.toString()};Ka.number=function(a,b){return a===b};Fa["function"]=!0;Ga["function"]=function(){return null};ra["function"]=!0;La._=function(a){return a[aa]||(a[aa]=++ba)};function ib(a){return a+1}
var jb=function(){function a(a,b,c,d){for(var l=y(a);;)if(d<l)c=b.a?b.a(c,z.a(a,d)):b.call(null,c,z.a(a,d)),d+=1;else return c}function b(a,b,c){for(var d=y(a),l=0;;)if(l<d)c=b.a?b.a(c,z.a(a,l)):b.call(null,c,z.a(a,l)),l+=1;else return c}function c(a,b){var c=y(a);if(0===c)return b.s?b.s():b.call(null);for(var d=z.a(a,0),l=1;;)if(l<c)d=b.a?b.a(d,z.a(a,l)):b.call(null,d,z.a(a,l)),l+=1;else return d}var d=null,d=function(d,g,h,k){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,
d,g,h);case 4:return a.call(this,d,g,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.i=a;return d}(),kb=function(){function a(a,b,c,d){for(var l=a.length;;)if(d<l)c=b.a?b.a(c,a[d]):b.call(null,c,a[d]),d+=1;else return c}function b(a,b,c){for(var d=a.length,l=0;;)if(l<d)c=b.a?b.a(c,a[l]):b.call(null,c,a[l]),l+=1;else return c}function c(a,b){var c=a.length;if(0===a.length)return b.s?b.s():b.call(null);for(var d=a[0],l=1;;)if(l<c)d=b.a?b.a(d,a[l]):b.call(null,d,a[l]),l+=1;else return d}
var d=null,d=function(d,g,h,k){switch(arguments.length){case 2:return c.call(this,d,g);case 3:return b.call(this,d,g,h);case 4:return a.call(this,d,g,h,k)}throw Error("Invalid arity: "+arguments.length);};d.a=c;d.c=b;d.i=a;return d}();function lb(a){return a?a.f&2||a.$a?!0:a.f?!1:s(sa,a):s(sa,a)}function mb(a){return a?a.f&16||a.Sa?!0:a.f?!1:s(ua,a):s(ua,a)}function hb(a,b){this.b=a;this.k=b;this.f=166199550;this.o=8192}f=hb.prototype;f.w=function(){return nb.d?nb.d(this):nb.call(null,this)};
f.Z=function(){return this.k+1<this.b.length?new hb(this.b,this.k+1):null};f.B=function(a,b){return S.a?S.a(b,this):S.call(null,b,this)};f.toString=function(){return H(this)};f.N=function(a,b){return kb.i(this.b,b,this.b[this.k],this.k+1)};f.O=function(a,b,c){return kb.i(this.b,b,c,this.k)};f.C=function(){return this};f.F=function(){return this.b.length-this.k};f.P=function(){return this.b[this.k]};f.Q=function(){return this.k+1<this.b.length?new hb(this.b,this.k+1):N};
f.t=function(a,b){return ob.a?ob.a(this,b):ob.call(null,this,b)};f.K=function(a,b){var c=b+this.k;return c<this.b.length?this.b[c]:null};f.S=function(a,b,c){a=b+this.k;return a<this.b.length?this.b[a]:c};
var pb=function(){function a(a,b){return b<a.length?new hb(a,b):null}function b(a){return c.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.a=a;return c}(),Q=function(){function a(a,b){return pb.a(a,b)}function b(a){return pb.a(a,0)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+
arguments.length);};c.d=b;c.a=a;return c}();function qb(a){for(;;){var b=P(a);if(null!=b)a=b;else return L(a)}}Ka._=function(a,b){return a===b};
var rb=function(){function a(a,b){return null!=a?ta(a,b):ta(N,b)}var b=null,c=function(){function a(b,d,k){var l=null;2<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,2),0));return c.call(this,b,d,l)}function c(a,d,e){for(;;)if(q(e))a=b.a(a,d),d=L(e),e=P(e);else return b.a(a,d)}a.m=2;a.h=function(a){var b=L(a);a=P(a);var d=L(a);a=M(a);return c(b,d,a)};a.g=c;return a}(),b=function(b,e,g){switch(arguments.length){case 2:return a.call(this,b,e);default:return c.g(b,e,Q(arguments,2))}throw Error("Invalid arity: "+
arguments.length);};b.m=2;b.h=c.h;b.a=a;b.g=c.g;return b}();function T(a){if(null!=a)if(a&&(a.f&2||a.$a))a=a.F(null);else if(a instanceof Array)a=a.length;else if("string"===typeof a)a=a.length;else if(s(sa,a))a=y(a);else if(t)a:{a=J(a);for(var b=0;;){if(lb(a)){a=b+y(a);break a}a=P(a);b+=1}a=void 0}else a=null;else a=0;return a}
var sb=function(){function a(a,b,c){for(;;){if(null==a)return c;if(0===b)return J(a)?L(a):c;if(mb(a))return z.c(a,b,c);if(J(a))a=P(a),b-=1;else return t?c:null}}function b(a,b){for(;;){if(null==a)throw Error("Index out of bounds");if(0===b){if(J(a))return L(a);throw Error("Index out of bounds");}if(mb(a))return z.a(a,b);if(J(a)){var c=P(a),h=b-1;a=c;b=h}else{if(t)throw Error("Index out of bounds");return null}}}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),tb=function(){function a(a,b,c){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return c;if(a&&(a.f&16||a.Sa))return a.S(null,b,c);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:c;if(s(ua,a))return z.a(a,b);if(a?a.f&64||a.sa||(a.f?0:s(va,a)):s(va,a))return sb.c(a,b,c);if(t)throw Error([w("nth not supported on this type "),w(qa(pa(a)))].join(""));return null}
function b(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number");if(null==a)return a;if(a&&(a.f&16||a.Sa))return a.K(null,b);if(a instanceof Array||"string"===typeof a)return b<a.length?a[b]:null;if(s(ua,a))return z.a(a,b);if(a?a.f&64||a.sa||(a.f?0:s(va,a)):s(va,a))return sb.a(a,b);if(t)throw Error([w("nth not supported on this type "),w(qa(pa(a)))].join(""));return null}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,
c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),ub=function(){function a(a,b,c){return null!=a?a&&(a.f&256||a.Ta)?a.M(null,b,c):a instanceof Array?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:s(wa,a)?C.c(a,b,c):t?c:null:c}function b(a,b){return null==a?null:a&&(a.f&256||a.Ta)?a.L(null,b):a instanceof Array?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:s(wa,a)?C.a(a,b):null}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),wb=function(){function a(a,b,c){return null!=a?xa(a,b,c):vb.a?vb.a([b],[c]):vb.call(null,[b],[c])}var b=null,c=function(){function a(b,d,k,l){var n=null;3<arguments.length&&(n=Q(Array.prototype.slice.call(arguments,3),0));return c.call(this,b,d,k,n)}function c(a,d,e,l){for(;;)if(a=b.c(a,d,e),q(l))d=L(l),e=L(P(l)),l=P(P(l));else return a}a.m=3;a.h=function(a){var b=L(a);a=P(a);var d=L(a);
a=P(a);var l=L(a);a=M(a);return c(b,d,l,a)};a.g=c;return a}(),b=function(b,e,g,h){switch(arguments.length){case 3:return a.call(this,b,e,g);default:return c.g(b,e,g,Q(arguments,3))}throw Error("Invalid arity: "+arguments.length);};b.m=3;b.h=c.h;b.c=a;b.g=c.g;return b}();function xb(a){var b="function"==m(a);return b?b:a?q(q(null)?null:a.pb)?!0:a.zb?!1:s(ra,a):s(ra,a)}function yb(a){var b=null!=a;return(b?a?a.f&131072||a.cb||(a.f?0:s(Fa,a)):s(Fa,a):b)?Ga(a):null}var zb={},Ab=0;
function I(a){if(a&&(a.f&4194304||a.sb))a=a.w(null);else if("number"===typeof a)a=Math.floor(a)%2147483647;else if(!0===a)a=1;else if(!1===a)a=0;else if("string"===typeof a){255<Ab&&(zb={},Ab=0);var b=zb[a];if("number"!==typeof b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;zb[a]=b;Ab+=1}a=b}else a=null==a?0:t?La(a):null;return a}function Bb(a){return a?a.f&16777216||a.wb?!0:a.f?!1:s(Oa,a):s(Oa,a)}function Db(a){return null==a?!1:a?a.f&1024||a.tb?!0:a.f?!1:s(za,a):s(za,a)}
function Eb(a){return a?a.f&16384||a.xb?!0:a.f?!1:s(Da,a):s(Da,a)}function Fb(a){return a?a.o&512||a.qb?!0:!1:!1}function Gb(a){var b=[];ca(a,function(a){return function(b,e){return a.push(e)}}(b));return b}function Hb(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,e-=1,b+=1}var Ib={};function Jb(a){return q(a)?!0:!1}
function db(a,b){if(a===b)return 0;if(null==a)return-1;if(null==b)return 1;if(pa(a)===pa(b))return a&&(a.o&2048||a.va)?a.wa(null,b):a>b?1:a<b?-1:0;if(t)throw Error("compare on non-nil objects of different types");return null}
var Kb=function(){function a(a,b,c,h){for(;;){var k=db(tb.a(a,h),tb.a(b,h));if(0===k&&h+1<c)h+=1;else return k}}function b(a,b){var g=T(a),h=T(b);return g<h?-1:g>h?1:t?c.i(a,b,g,0):null}var c=null,c=function(c,e,g,h){switch(arguments.length){case 2:return b.call(this,c,e);case 4:return a.call(this,c,e,g,h)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.i=a;return c}(),U=function(){function a(a,b,c){for(c=J(c);;)if(c)b=a.a?a.a(b,L(c)):a.call(null,b,L(c)),c=P(c);else return b}function b(a,
b){var c=J(b);return c?Lb.c?Lb.c(a,L(c),P(c)):Lb.call(null,a,L(c),P(c)):a.s?a.s():a.call(null)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),Lb=function(){function a(a,b,c){return c&&(c.f&524288||c.fb)?c.O(null,a,b):c instanceof Array?kb.c(c,a,b):"string"===typeof c?kb.c(c,a,b):s(Ia,c)?Ja.c(c,a,b):t?U.c(a,b,c):null}function b(a,b){return b&&(b.f&524288||
b.fb)?b.N(null,a):b instanceof Array?kb.a(b,a):"string"===typeof b?kb.a(b,a):s(Ia,b)?Ja.a(b,a):t?U.a(a,b):null}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Mb(a){return 0<=a?Math.floor.d?Math.floor.d(a):Math.floor.call(null,a):Math.ceil.d?Math.ceil.d(a):Math.ceil.call(null,a)}function Nb(a){return Mb((a-a%2)/2)}
var Ob=function(){function a(a){return a*c.s()}function b(){return Math.random.s?Math.random.s():Math.random.call(null)}var c=null,c=function(c){switch(arguments.length){case 0:return b.call(this);case 1:return a.call(this,c)}throw Error("Invalid arity: "+arguments.length);};c.s=b;c.d=a;return c}();function Pb(a){return Mb(Ob.d(a))}function Qb(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}
var w=function(){function a(a){return null==a?"":a.toString()}var b=null,c=function(){function a(b,d){var k=null;1<arguments.length&&(k=Q(Array.prototype.slice.call(arguments,1),0));return c.call(this,b,k)}function c(a,d){for(var e=new ea(b.d(a)),l=d;;)if(q(l))e=e.append(b.d(L(l))),l=P(l);else return e.toString()}a.m=1;a.h=function(a){var b=L(a);a=M(a);return c(b,a)};a.g=c;return a}(),b=function(b,e){switch(arguments.length){case 0:return"";case 1:return a.call(this,b);default:return c.g(b,Q(arguments,
1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.h=c.h;b.s=function(){return""};b.d=a;b.g=c.g;return b}();function ob(a,b){return Jb(Bb(b)?function(){for(var c=J(a),d=J(b);;){if(null==c)return null==d;if(null==d)return!1;if(cb.a(L(c),L(d)))c=P(c),d=P(d);else return t?!1:null}}():null)}function gb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function nb(a){if(J(a)){var b=I(L(a));for(a=P(a);;){if(null==a)return b;b=gb(b,I(L(a)));a=P(a)}}else return 0}
function Rb(a){var b=0;for(a=J(a);;)if(a){var c=L(a),b=(b+(I(Sb.d?Sb.d(c):Sb.call(null,c))^I(Tb.d?Tb.d(c):Tb.call(null,c))))%4503599627370496;a=P(a)}else return b}function Ub(a,b,c,d,e){this.l=a;this.first=b;this.da=c;this.count=d;this.j=e;this.f=65937646;this.o=8192}f=Ub.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.Z=function(){return 1===this.count?null:this.da};f.B=function(a,b){return new Ub(this.l,b,this,this.count+1,null)};f.toString=function(){return H(this)};
f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){return this};f.F=function(){return this.count};f.P=function(){return this.first};f.Q=function(){return 1===this.count?N:this.da};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new Ub(b,this.first,this.da,this.count,this.j)};f.G=function(){return this.l};function Vb(a){this.l=a;this.f=65937614;this.o=8192}f=Vb.prototype;f.w=function(){return 0};f.Z=function(){return null};
f.B=function(a,b){return new Ub(this.l,b,null,1,null)};f.toString=function(){return H(this)};f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){return null};f.F=function(){return 0};f.P=function(){return null};f.Q=function(){return N};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new Vb(b)};f.G=function(){return this.l};
var N=new Vb(null),Wb=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b;if(a instanceof hb&&0===a.k)b=a.b;else a:{for(b=[];;)if(null!=a)b.push(a.P(null)),a=a.Z(null);else break a;b=void 0}a=b.length;for(var e=N;;)if(0<a){var g=a-1,e=e.B(null,b[a-1]);a=g}else return e}a.m=0;a.h=function(a){a=J(a);return b(a)};a.g=b;return a}();
function Xb(a,b,c,d){this.l=a;this.first=b;this.da=c;this.j=d;this.f=65929452;this.o=8192}f=Xb.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.Z=function(){return null==this.da?null:J(this.da)};f.B=function(a,b){return new Xb(null,b,this,this.j)};f.toString=function(){return H(this)};f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){return this};f.P=function(){return this.first};f.Q=function(){return null==this.da?N:this.da};
f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new Xb(b,this.first,this.da,this.j)};f.G=function(){return this.l};function S(a,b){var c=null==b;return(c?c:b&&(b.f&64||b.sa))?new Xb(null,a,b,null):new Xb(null,a,J(b),null)}function V(a,b,c,d){this.J=a;this.name=b;this.fa=c;this.ha=d;this.f=2153775105;this.o=4096}f=V.prototype;f.u=function(a,b){return G(b,[w(":"),w(this.fa)].join(""))};f.w=function(){null==this.ha&&(this.ha=gb(I(this.J),I(this.name))+2654435769);return this.ha};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return ub.a(c,this);case 3:return ub.c(c,this,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return ub.a(a,this)};f.a=function(a,b){return ub.c(a,this,b)};f.t=function(a,b){return b instanceof V?this.fa===b.fa:!1};f.toString=function(){return[w(":"),w(this.fa)].join("")};
var Zb=function(){function a(a,b){return new V(a,b,[w(q(a)?[w(a),w("/")].join(""):null),w(b)].join(""),null)}function b(a){if(a instanceof V)return a;if(a instanceof fb){var b;if(a&&(a.o&4096||a.eb))b=a.J;else throw Error([w("Doesn't support namespace: "),w(a)].join(""));return new V(b,Yb.d?Yb.d(a):Yb.call(null,a),a.ga,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new V(b[0],b[1],a,null):new V(null,b[0],a,null)):null}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,
c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.a=a;return c}();function W(a,b,c,d){this.l=a;this.na=b;this.p=c;this.j=d;this.o=0;this.f=32374988}f=W.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.Z=function(){Na(this);return null==this.p?null:P(this.p)};f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};function $b(a){null!=a.na&&(a.p=a.na.s?a.na.s():a.na.call(null),a.na=null);return a.p}
f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){$b(this);if(null==this.p)return null;for(var a=this.p;;)if(a instanceof W)a=$b(a);else return this.p=a,J(this.p)};f.P=function(){Na(this);return null==this.p?null:L(this.p)};f.Q=function(){Na(this);return null!=this.p?M(this.p):N};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new W(b,this.na,this.p,this.j)};f.G=function(){return this.l};
function ac(a,b){this.za=a;this.end=b;this.o=0;this.f=2}ac.prototype.F=function(){return this.end};ac.prototype.add=function(a){this.za[this.end]=a;return this.end+=1};ac.prototype.V=function(){var a=new bc(this.za,0,this.end);this.za=null;return a};function bc(a,b,c){this.b=a;this.q=b;this.end=c;this.o=0;this.f=524306}f=bc.prototype;f.N=function(a,b){return kb.i(this.b,b,this.b[this.q],this.q+1)};f.O=function(a,b,c){return kb.i(this.b,b,c,this.q)};
f.Ra=function(){if(this.q===this.end)throw Error("-drop-first of empty chunk");return new bc(this.b,this.q+1,this.end)};f.K=function(a,b){return this.b[this.q+b]};f.S=function(a,b,c){return 0<=b&&b<this.end-this.q?this.b[this.q+b]:c};f.F=function(){return this.end-this.q};
var cc=function(){function a(a,b,c){return new bc(a,b,c)}function b(a,b){return new bc(a,b,a.length)}function c(a){return new bc(a,0,a.length)}var d=null,d=function(d,g,h){switch(arguments.length){case 1:return c.call(this,d);case 2:return b.call(this,d,g);case 3:return a.call(this,d,g,h)}throw Error("Invalid arity: "+arguments.length);};d.d=c;d.a=b;d.c=a;return d}();function dc(a,b,c,d){this.V=a;this.$=b;this.l=c;this.j=d;this.f=31850732;this.o=1536}f=dc.prototype;
f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.Z=function(){if(1<y(this.V))return new dc(Xa(this.V),this.$,this.l,null);var a=Na(this.$);return null==a?null:a};f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};f.C=function(){return this};f.P=function(){return z.a(this.V,0)};f.Q=function(){return 1<y(this.V)?new dc(Xa(this.V),this.$,this.l,null):null==this.$?N:this.$};f.Aa=function(){return null==this.$?null:this.$};f.t=function(a,b){return ob(this,b)};
f.I=function(a,b){return new dc(this.V,this.$,b,this.j)};f.G=function(){return this.l};f.Ba=function(){return this.V};f.Ca=function(){return null==this.$?N:this.$};function ec(a,b){return 0===y(a)?b:new dc(a,b,null,null)}function fc(a){for(var b=[];;)if(J(a))b.push(L(a)),a=P(a);else return b}function gc(a,b){if(lb(a))return T(a);for(var c=a,d=b,e=0;;)if(0<d&&J(c))c=P(c),d-=1,e+=1;else return e}
var ic=function hc(b){return null==b?null:null==P(b)?J(L(b)):t?S(L(b),hc(P(b))):null},jc=function(){function a(a,b){return new W(null,function(){var c=J(a);return c?Fb(c)?ec(Ya(c),d.a(Za(c),b)):S(L(c),d.a(M(c),b)):b},null,null)}function b(a){return new W(null,function(){return a},null,null)}function c(){return new W(null,function(){return null},null,null)}var d=null,e=function(){function a(c,d,e){var g=null;2<arguments.length&&(g=Q(Array.prototype.slice.call(arguments,2),0));return b.call(this,c,
d,g)}function b(a,c,e){return function r(a,b){return new W(null,function(){var c=J(a);return c?Fb(c)?ec(Ya(c),r(Za(c),b)):S(L(c),r(M(c),b)):q(b)?r(L(b),P(b)):null},null,null)}(d.a(a,c),e)}a.m=2;a.h=function(a){var c=L(a);a=P(a);var d=L(a);a=M(a);return b(c,d,a)};a.g=b;return a}(),d=function(d,h,k){switch(arguments.length){case 0:return c.call(this);case 1:return b.call(this,d);case 2:return a.call(this,d,h);default:return e.g(d,h,Q(arguments,2))}throw Error("Invalid arity: "+arguments.length);};d.m=
2;d.h=e.h;d.s=c;d.d=b;d.a=a;d.g=e.g;return d}(),kc=function(){function a(a,b,c,d){return S(a,S(b,S(c,d)))}function b(a,b,c){return S(a,S(b,c))}var c=null,d=function(){function a(c,d,e,n,p){var r=null;4<arguments.length&&(r=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,n,r)}function b(a,c,d,e,g){return S(a,S(c,S(d,S(e,ic(g)))))}a.m=4;a.h=function(a){var c=L(a);a=P(a);var d=L(a);a=P(a);var e=L(a);a=P(a);var p=L(a);a=M(a);return b(c,d,e,p,a)};a.g=b;return a}(),c=function(c,g,
h,k,l){switch(arguments.length){case 1:return J(c);case 2:return S(c,g);case 3:return b.call(this,c,g,h);case 4:return a.call(this,c,g,h,k);default:return d.g(c,g,h,k,Q(arguments,4))}throw Error("Invalid arity: "+arguments.length);};c.m=4;c.h=d.h;c.d=function(a){return J(a)};c.a=function(a,b){return S(a,b)};c.c=b;c.i=a;c.g=d.g;return c}(),lc=function(){var a=null,b=function(){function a(c,g,h){var k=null;2<arguments.length&&(k=Q(Array.prototype.slice.call(arguments,2),0));return b.call(this,c,g,k)}
function b(a,c,d){for(;;)if(a=Ta(a,c),q(d))c=L(d),d=P(d);else return a}a.m=2;a.h=function(a){var c=L(a);a=P(a);var h=L(a);a=M(a);return b(c,h,a)};a.g=b;return a}(),a=function(a,d,e){switch(arguments.length){case 2:return Ta(a,d);default:return b.g(a,d,Q(arguments,2))}throw Error("Invalid arity: "+arguments.length);};a.m=2;a.h=b.h;a.a=function(a,b){return Ta(a,b)};a.g=b.g;return a}(),mc=function(){var a=null,b=function(){function a(c,g,h,k){var l=null;3<arguments.length&&(l=Q(Array.prototype.slice.call(arguments,
3),0));return b.call(this,c,g,h,l)}function b(a,c,d,k){for(;;)if(a=Va(a,c,d),q(k))c=L(k),d=L(P(k)),k=P(P(k));else return a}a.m=3;a.h=function(a){var c=L(a);a=P(a);var h=L(a);a=P(a);var k=L(a);a=M(a);return b(c,h,k,a)};a.g=b;return a}(),a=function(a,d,e,g){switch(arguments.length){case 3:return Va(a,d,e);default:return b.g(a,d,e,Q(arguments,3))}throw Error("Invalid arity: "+arguments.length);};a.m=3;a.h=b.h;a.c=function(a,b,e){return Va(a,b,e)};a.g=b.g;return a}();
function nc(a,b,c){var d=J(c);if(0===b)return a.s?a.s():a.call(null);c=A(d);var e=B(d);if(1===b)return a.d?a.d(c):a.d?a.d(c):a.call(null,c);var d=A(e),g=B(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=A(g),h=B(g);if(3===b)return a.c?a.c(c,d,e):a.c?a.c(c,d,e):a.call(null,c,d,e);var g=A(h),k=B(h);if(4===b)return a.i?a.i(c,d,e,g):a.i?a.i(c,d,e,g):a.call(null,c,d,e,g);var h=A(k),l=B(k);if(5===b)return a.A?a.A(c,d,e,g,h):a.A?a.A(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=A(l),n=B(l);
if(6===b)return a.ca?a.ca(c,d,e,g,h,k):a.ca?a.ca(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=A(n),p=B(n);if(7===b)return a.ka?a.ka(c,d,e,g,h,k,l):a.ka?a.ka(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var n=A(p),r=B(p);if(8===b)return a.Oa?a.Oa(c,d,e,g,h,k,l,n):a.Oa?a.Oa(c,d,e,g,h,k,l,n):a.call(null,c,d,e,g,h,k,l,n);var p=A(r),u=B(r);if(9===b)return a.Pa?a.Pa(c,d,e,g,h,k,l,n,p):a.Pa?a.Pa(c,d,e,g,h,k,l,n,p):a.call(null,c,d,e,g,h,k,l,n,p);var r=A(u),E=B(u);if(10===b)return a.Da?a.Da(c,d,e,g,h,k,l,n,p,
r):a.Da?a.Da(c,d,e,g,h,k,l,n,p,r):a.call(null,c,d,e,g,h,k,l,n,p,r);var u=A(E),D=B(E);if(11===b)return a.Ea?a.Ea(c,d,e,g,h,k,l,n,p,r,u):a.Ea?a.Ea(c,d,e,g,h,k,l,n,p,r,u):a.call(null,c,d,e,g,h,k,l,n,p,r,u);var E=A(D),K=B(D);if(12===b)return a.Fa?a.Fa(c,d,e,g,h,k,l,n,p,r,u,E):a.Fa?a.Fa(c,d,e,g,h,k,l,n,p,r,u,E):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E);var D=A(K),O=B(K);if(13===b)return a.Ga?a.Ga(c,d,e,g,h,k,l,n,p,r,u,E,D):a.Ga?a.Ga(c,d,e,g,h,k,l,n,p,r,u,E,D):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D);var K=A(O),
R=B(O);if(14===b)return a.Ha?a.Ha(c,d,e,g,h,k,l,n,p,r,u,E,D,K):a.Ha?a.Ha(c,d,e,g,h,k,l,n,p,r,u,E,D,K):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D,K);var O=A(R),da=B(R);if(15===b)return a.Ia?a.Ia(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O):a.Ia?a.Ia(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D,K,O);var R=A(da),ga=B(da);if(16===b)return a.Ja?a.Ja(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R):a.Ja?a.Ja(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R);var da=A(ga),ya=B(ga);if(17===
b)return a.Ka?a.Ka(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da):a.Ka?a.Ka(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da);var ga=A(ya),Cb=B(ya);if(18===b)return a.La?a.La(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga):a.La?a.La(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga);ya=A(Cb);Cb=B(Cb);if(19===b)return a.Ma?a.Ma(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga,ya):a.Ma?a.Ma(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga,ya):a.call(null,c,d,e,g,h,k,l,
n,p,r,u,E,D,K,O,R,da,ga,ya);var sc=A(Cb);B(Cb);if(20===b)return a.Na?a.Na(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga,ya,sc):a.Na?a.Na(c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga,ya,sc):a.call(null,c,d,e,g,h,k,l,n,p,r,u,E,D,K,O,R,da,ga,ya,sc);throw Error("Only up to 20 arguments supported on functions");}
var oc=function(){function a(a,b,c,d,e){b=kc.i(b,c,d,e);c=a.m;return a.h?(d=gc(b,c+1),d<=c?nc(a,d,b):a.h(b)):a.apply(a,fc(b))}function b(a,b,c,d){b=kc.c(b,c,d);c=a.m;return a.h?(d=gc(b,c+1),d<=c?nc(a,d,b):a.h(b)):a.apply(a,fc(b))}function c(a,b,c){b=kc.a(b,c);c=a.m;if(a.h){var d=gc(b,c+1);return d<=c?nc(a,d,b):a.h(b)}return a.apply(a,fc(b))}function d(a,b){var c=a.m;if(a.h){var d=gc(b,c+1);return d<=c?nc(a,d,b):a.h(b)}return a.apply(a,fc(b))}var e=null,g=function(){function a(c,d,e,g,h,E){var D=null;
5<arguments.length&&(D=Q(Array.prototype.slice.call(arguments,5),0));return b.call(this,c,d,e,g,h,D)}function b(a,c,d,e,g,h){c=S(c,S(d,S(e,S(g,ic(h)))));d=a.m;return a.h?(e=gc(c,d+1),e<=d?nc(a,e,c):a.h(c)):a.apply(a,fc(c))}a.m=5;a.h=function(a){var c=L(a);a=P(a);var d=L(a);a=P(a);var e=L(a);a=P(a);var g=L(a);a=P(a);var h=L(a);a=M(a);return b(c,d,e,g,h,a)};a.g=b;return a}(),e=function(e,k,l,n,p,r){switch(arguments.length){case 2:return d.call(this,e,k);case 3:return c.call(this,e,k,l);case 4:return b.call(this,
e,k,l,n);case 5:return a.call(this,e,k,l,n,p);default:return g.g(e,k,l,n,p,Q(arguments,5))}throw Error("Invalid arity: "+arguments.length);};e.m=5;e.h=g.h;e.a=d;e.c=c;e.i=b;e.A=a;e.g=g.g;return e}();function pc(a,b){for(;;){if(null==J(b))return!0;if(q(a.d?a.d(L(b)):a.call(null,L(b)))){var c=a,d=P(b);a=c;b=d}else return t?!1:null}}function qc(a){return a}
function rc(a,b){return function d(b,g){return new W(null,function(){var h=J(g);if(h){if(Fb(h)){for(var k=Ya(h),l=T(k),n=new ac(Array(l),0),p=0;;)if(p<l){var r=a.a?a.a(b+p,z.a(k,p)):a.call(null,b+p,z.a(k,p));null!=r&&n.add(r);p+=1}else break;return ec(n.V(),d(b+l,Za(h)))}k=a.a?a.a(b,L(h)):a.call(null,b,L(h));return null==k?d(b+1,M(h)):S(k,d(b+1,M(h)))}return null},null,null)}(0,b)}
var tc=function(){function a(a,b,c,e){return new W(null,function(){var n=J(b),p=J(c),r=J(e);return n&&p&&r?S(a.c?a.c(L(n),L(p),L(r)):a.call(null,L(n),L(p),L(r)),d.i(a,M(n),M(p),M(r))):null},null,null)}function b(a,b,c){return new W(null,function(){var e=J(b),n=J(c);return e&&n?S(a.a?a.a(L(e),L(n)):a.call(null,L(e),L(n)),d.c(a,M(e),M(n))):null},null,null)}function c(a,b){return new W(null,function(){var c=J(b);if(c){if(Fb(c)){for(var e=Ya(c),n=T(e),p=new ac(Array(n),0),r=0;;)if(r<n){var u=a.d?a.d(z.a(e,
r)):a.call(null,z.a(e,r));p.add(u);r+=1}else break;return ec(p.V(),d.a(a,Za(c)))}return S(a.d?a.d(L(c)):a.call(null,L(c)),d.a(a,M(c)))}return null},null,null)}var d=null,e=function(){function a(c,d,e,g,r){var u=null;4<arguments.length&&(u=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,g,u)}function b(a,c,e,g,h){var u=function D(a){return new W(null,function(){var b=d.a(J,a);return pc(qc,b)?S(d.a(L,b),D(d.a(M,b))):null},null,null)};return d.a(function(){return function(b){return oc.a(a,
b)}}(u),u(rb.g(h,g,Q([e,c],0))))}a.m=4;a.h=function(a){var c=L(a);a=P(a);var d=L(a);a=P(a);var e=L(a);a=P(a);var g=L(a);a=M(a);return b(c,d,e,g,a)};a.g=b;return a}(),d=function(d,h,k,l,n){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.g(d,h,k,l,Q(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.h=e.h;d.a=c;d.c=b;d.i=a;d.g=e.g;return d}(),vc=function uc(b,c){return new W(null,function(){if(0<
b){var d=J(c);return d?S(L(d),uc(b-1,M(d))):null}return null},null,null)},wc=function(){function a(a,b){return vc(a,c.d(b))}function b(a){return new W(null,function(){return S(a,c.d(a))},null,null)}var c=null,c=function(c,e){switch(arguments.length){case 1:return b.call(this,c);case 2:return a.call(this,c,e)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.a=a;return c}(),yc=function xc(b,c){return new W(null,function(){var d=J(c);if(d){if(Fb(d)){for(var e=Ya(d),g=T(e),h=new ac(Array(g),
0),k=0;;)if(k<g){if(q(b.d?b.d(z.a(e,k)):b.call(null,z.a(e,k)))){var l=z.a(e,k);h.add(l)}k+=1}else break;return ec(h.V(),xc(b,Za(d)))}e=L(d);d=M(d);return q(b.d?b.d(e):b.call(null,e))?S(e,xc(b,d)):xc(b,d)}return null},null,null)},zc=function(){function a(a,b,c){var h=Ib;for(b=J(b);;)if(b){var k=a;if(k?k.f&256||k.Ta||(k.f?0:s(wa,k)):s(wa,k)){a=ub.c(a,L(b),h);if(h===a)return c;b=P(b)}else return c}else return a}function b(a,b){return c.c(a,b,null)}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,
c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}(),Bc=function Ac(b,c,d){var e=tb.c(c,0,null),g;a:{g=1;for(c=J(c);;)if(c&&0<g)g-=1,c=P(c);else{g=c;break a}g=void 0}return g?wb.c(b,e,Ac(ub.a(b,e),g,d)):wb.c(b,e,d)};function Cc(a,b){this.n=a;this.b=b}
function Dc(a){return new Cc(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Ec(a){a=a.e;return 32>a?0:a-1>>>5<<5}function Fc(a,b,c){for(;;){if(0===b)return c;var d=Dc(a);d.b[0]=c;c=d;b-=5}}var Hc=function Gc(b,c,d,e){var g=new Cc(d.n,x(d.b)),h=b.e-1>>>c&31;5===c?g.b[h]=e:(d=d.b[h],b=null!=d?Gc(b,c-5,d,e):Fc(null,c-5,e),g.b[h]=b);return g};
function Ic(a,b){throw Error([w("No item "),w(a),w(" in vector of length "),w(b)].join(""));}function Jc(a){var b=a.root;for(a=a.shift;;)if(0<a)a-=5,b=b.b[0];else return b.b}function Kc(a,b){if(b>=Ec(a))return a.D;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.b[b>>>d&31],d=e;else return c.b}function Lc(a,b){return 0<=b&&b<a.e?Kc(a,b):Ic(b,a.e)}var Nc=function Mc(b,c,d,e,g){var h=new Cc(d.n,x(d.b));if(0===c)h.b[e&31]=g;else{var k=e>>>c&31;b=Mc(b,c-5,d.b[k],e,g);h.b[k]=b}return h};
function X(a,b,c,d,e,g){this.l=a;this.e=b;this.shift=c;this.root=d;this.D=e;this.j=g;this.o=8196;this.f=167668511}f=X.prototype;f.ra=function(){return new Oc(this.e,this.shift,Pc.d?Pc.d(this.root):Pc.call(null,this.root),Qc.d?Qc.d(this.D):Qc.call(null,this.D))};f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.L=function(a,b){return C.c(this,b,null)};f.M=function(a,b,c){return"number"===typeof b?z.c(this,b,c):c};
f.qa=function(a,b,c){if("number"===typeof b)return Ea(this,b,c);throw Error("Vector's key for assoc must be a number.");};f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.S(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return this.K(null,a)};f.a=function(a,b){return this.S(null,a,b)};
f.B=function(a,b){if(32>this.e-Ec(this)){for(var c=this.D.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.D[e],e+=1;else break;d[c]=b;return new X(this.l,this.e+1,this.shift,this.root,d,null)}c=(d=this.e>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Dc(null),d.b[0]=this.root,e=Fc(null,this.shift,new Cc(null,this.D)),d.b[1]=e):d=Hc(this,this.shift,this.root,new Cc(null,this.D));return new X(this.l,this.e+1,c,d,[b],null)};f.Ua=function(){return z.a(this,0)};f.Va=function(){return z.a(this,1)};
f.toString=function(){return H(this)};f.N=function(a,b){return jb.a(this,b)};f.O=function(a,b,c){return jb.c(this,b,c)};f.C=function(){return 0===this.e?null:32>=this.e?new hb(this.D,0):t?Y.i?Y.i(this,Jc(this),0,0):Y.call(null,this,Jc(this),0,0):null};f.F=function(){return this.e};
f.Qa=function(a,b,c){if(0<=b&&b<this.e)return Ec(this)<=b?(a=x(this.D),a[b&31]=c,new X(this.l,this.e,this.shift,this.root,a,null)):new X(this.l,this.e,this.shift,Nc(this,this.shift,this.root,b,c),this.D,null);if(b===this.e)return ta(this,c);if(t)throw Error([w("Index "),w(b),w(" out of bounds  [0,"),w(this.e),w("]")].join(""));return null};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new X(b,this.e,this.shift,this.root,this.D,this.j)};f.G=function(){return this.l};
f.K=function(a,b){return Lc(this,b)[b&31]};f.S=function(a,b,c){return 0<=b&&b<this.e?Kc(this,b)[b&31]:c};var Z=new Cc(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Rc=new X(null,0,5,Z,[],0);
function Sc(a,b){var c=a.length,d=b?a:x(a);if(32>c)return new X(null,c,5,Z,d,null);for(var e=32,g=(new X(null,32,5,Z,d.slice(0,32),null)).ra(null);;)if(e<c)var h=e+1,g=lc.a(g,d[e]),e=h;else return Ua(g)}var Tc=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){return a instanceof hb&&0===a.k?Sc.a?Sc.a(a.b,!0):Sc.call(null,a.b,!0):Ua(Lb.c(Ta,Sa(Rc),a))}a.m=0;a.h=function(a){a=J(a);return b(a)};a.g=b;return a}();
function Uc(a,b,c,d,e,g){this.r=a;this.U=b;this.k=c;this.q=d;this.l=e;this.j=g;this.f=32243948;this.o=1536}f=Uc.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.Z=function(){if(this.q+1<this.U.length){var a=Y.i?Y.i(this.r,this.U,this.k,this.q+1):Y.call(null,this.r,this.U,this.k,this.q+1);return null==a?null:a}return $a(this)};f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};
f.N=function(a,b){return jb.a(Vc.c?Vc.c(this.r,this.k+this.q,T(this.r)):Vc.call(null,this.r,this.k+this.q,T(this.r)),b)};f.O=function(a,b,c){return jb.c(Vc.c?Vc.c(this.r,this.k+this.q,T(this.r)):Vc.call(null,this.r,this.k+this.q,T(this.r)),b,c)};f.C=function(){return this};f.P=function(){return this.U[this.q]};f.Q=function(){if(this.q+1<this.U.length){var a=Y.i?Y.i(this.r,this.U,this.k,this.q+1):Y.call(null,this.r,this.U,this.k,this.q+1);return null==a?N:a}return Za(this)};
f.Aa=function(){var a=this.k+this.U.length;return a<y(this.r)?Y.i?Y.i(this.r,Kc(this.r,a),a,0):Y.call(null,this.r,Kc(this.r,a),a,0):null};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return Y.A?Y.A(this.r,this.U,this.k,this.q,b):Y.call(null,this.r,this.U,this.k,this.q,b)};f.Ba=function(){return cc.a(this.U,this.q)};f.Ca=function(){var a=this.k+this.U.length;return a<y(this.r)?Y.i?Y.i(this.r,Kc(this.r,a),a,0):Y.call(null,this.r,Kc(this.r,a),a,0):N};
var Y=function(){function a(a,b,c,d,l){return new Uc(a,b,c,d,l,null)}function b(a,b,c,d){return new Uc(a,b,c,d,null,null)}function c(a,b,c){return new Uc(a,Lc(a,b),b,c,null,null)}var d=null,d=function(d,g,h,k,l){switch(arguments.length){case 3:return c.call(this,d,g,h);case 4:return b.call(this,d,g,h,k);case 5:return a.call(this,d,g,h,k,l)}throw Error("Invalid arity: "+arguments.length);};d.c=c;d.i=b;d.A=a;return d}();
function Wc(a,b,c,d,e){this.l=a;this.aa=b;this.start=c;this.end=d;this.j=e;this.f=166617887;this.o=8192}f=Wc.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.L=function(a,b){return C.c(this,b,null)};f.M=function(a,b,c){return"number"===typeof b?z.c(this,b,c):c};f.qa=function(a,b,c){if("number"===typeof b)return Ea(this,b,c);throw Error("Subvec's key for assoc must be a number.");};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.K(null,c);case 3:return this.S(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return this.K(null,a)};f.a=function(a,b){return this.S(null,a,b)};
f.B=function(a,b){return Xc.A?Xc.A(this.l,Ea(this.aa,this.end,b),this.start,this.end+1,null):Xc.call(null,this.l,Ea(this.aa,this.end,b),this.start,this.end+1,null)};f.toString=function(){return H(this)};f.N=function(a,b){return jb.a(this,b)};f.O=function(a,b,c){return jb.c(this,b,c)};f.C=function(){var a=this;return function(b){return function d(e){return e===a.end?null:S(z.a(a.aa,e),new W(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};
f.F=function(){return this.end-this.start};f.Qa=function(a,b,c){var d=this,e=d.start+b;return Xc.A?Xc.A(d.l,wb.c(d.aa,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null):Xc.call(null,d.l,wb.c(d.aa,e,c),d.start,function(){var a=d.end,b=e+1;return a>b?a:b}(),null)};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return Xc.A?Xc.A(b,this.aa,this.start,this.end,this.j):Xc.call(null,b,this.aa,this.start,this.end,this.j)};f.G=function(){return this.l};
f.K=function(a,b){return 0>b||this.end<=this.start+b?Ic(b,this.end-this.start):z.a(this.aa,this.start+b)};f.S=function(a,b,c){return 0>b||this.end<=this.start+b?c:z.c(this.aa,this.start+b,c)};function Xc(a,b,c,d,e){for(;;)if(b instanceof Wc)c=b.start+c,d=b.start+d,b=b.aa;else{var g=T(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new Wc(a,b,c,d,e)}}
var Vc=function(){function a(a,b,c){return Xc(null,a,b,c,null)}function b(a,b){return c.c(a,b,T(a))}var c=null,c=function(c,e,g){switch(arguments.length){case 2:return b.call(this,c,e);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.a=b;c.c=a;return c}();function Yc(a,b){return a===b.n?b:new Cc(a,x(b.b))}function Pc(a){return new Cc({},x(a.b))}
function Qc(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Hb(a,0,b,0,a.length);return b}var $c=function Zc(b,c,d,e){d=Yc(b.root.n,d);var g=b.e-1>>>c&31;if(5===c)b=e;else{var h=d.b[g];b=null!=h?Zc(b,c-5,h,e):Fc(b.root.n,c-5,e)}d.b[g]=b;return d};function Oc(a,b,c,d){this.e=a;this.shift=b;this.root=c;this.D=d;this.f=275;this.o=88}f=Oc.prototype;
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return this.L(null,a)};f.a=function(a,b){return this.M(null,a,b)};f.L=function(a,b){return C.c(this,b,null)};f.M=function(a,b,c){return"number"===typeof b?z.c(this,b,c):c};
f.K=function(a,b){if(this.root.n)return Lc(this,b)[b&31];throw Error("nth after persistent!");};f.S=function(a,b,c){return 0<=b&&b<this.e?z.a(this,b):c};f.F=function(){if(this.root.n)return this.e;throw Error("count after persistent!");};
f.Wa=function(a,b,c){var d=this;if(d.root.n){if(0<=b&&b<d.e)return Ec(this)<=b?d.D[b&31]=c:(a=function(){return function g(a,k){var l=Yc(d.root.n,k);if(0===a)l.b[b&31]=c;else{var n=b>>>a&31,p=g(a-5,l.b[n]);l.b[n]=p}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.e)return Ta(this,c);if(t)throw Error([w("Index "),w(b),w(" out of bounds for TransientVector of length"),w(d.e)].join(""));return null}throw Error("assoc! after persistent!");};
f.ta=function(a,b,c){if("number"===typeof b)return Wa(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.xa=function(a,b){if(this.root.n){if(32>this.e-Ec(this))this.D[this.e&31]=b;else{var c=new Cc(this.root.n,this.D),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.D=d;if(this.e>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Fc(this.root.n,this.shift,c);this.root=new Cc(this.root.n,d);this.shift=e}else this.root=$c(this,this.shift,this.root,c)}this.e+=1;return this}throw Error("conj! after persistent!");};f.ya=function(){if(this.root.n){this.root.n=null;var a=this.e-Ec(this),b=Array(a);Hb(this.D,0,b,0,a);return new X(null,this.e,this.shift,this.root,b,null)}throw Error("persistent! called twice");};function ad(){this.o=0;this.f=2097152}ad.prototype.t=function(){return!1};var bd=new ad;
function cd(a,b){return Jb(Db(b)?T(a)===T(b)?pc(qc,tc.a(function(a){return cb.a(ub.c(b,L(a),bd),L(P(a)))},a)):null:null)}
function dd(a,b){var c=a.b;if(b instanceof V)a:{for(var d=c.length,e=b.fa,g=0;;){if(d<=g){c=-1;break a}var h=c[g];if(h instanceof V&&e===h.fa){c=g;break a}if(t)g+=2;else{c=null;break a}}c=void 0}else if("string"==typeof b||"number"===typeof b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(b===c[e]){c=e;break a}if(t)e+=2;else{c=null;break a}}c=void 0}else if(b instanceof fb)a:{d=c.length;e=b.ga;for(g=0;;){if(d<=g){c=-1;break a}h=c[g];if(h instanceof fb&&e===h.ga){c=g;break a}if(t)g+=2;else{c=null;
break a}}c=void 0}else if(null==b)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(null==c[e]){c=e;break a}if(t)e+=2;else{c=null;break a}}c=void 0}else if(t)a:{d=c.length;for(e=0;;){if(d<=e){c=-1;break a}if(cb.a(b,c[e])){c=e;break a}if(t)e+=2;else{c=null;break a}}c=void 0}else c=null;return c}function ed(a,b,c){this.b=a;this.k=b;this.oa=c;this.o=0;this.f=32374990}f=ed.prototype;f.w=function(){return nb(this)};f.Z=function(){return this.k<this.b.length-2?new ed(this.b,this.k+2,this.oa):null};
f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){return this};f.F=function(){return(this.b.length-this.k)/2};f.P=function(){return new X(null,2,5,Z,[this.b[this.k],this.b[this.k+1]],null)};f.Q=function(){return this.k<this.b.length-2?new ed(this.b,this.k+2,this.oa):N};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new ed(this.b,this.k,b)};f.G=function(){return this.oa};
function ia(a,b,c,d){this.l=a;this.e=b;this.b=c;this.j=d;this.o=8196;this.f=16123663}f=ia.prototype;f.ra=function(){return new fd({},this.b.length,x(this.b))};f.w=function(){var a=this.j;return null!=a?a:this.j=a=Rb(this)};f.L=function(a,b){return C.c(this,b,null)};f.M=function(a,b,c){a=dd(this,b);return-1===a?c:this.b[a+1]};
f.qa=function(a,b,c){a=dd(this,b);if(-1===a){if(this.e<gd){a=this.b;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new ia(this.l,this.e+1,e,null)}a=Ha;d=xa;e=hd;null!=e?e&&(e.o&4||e.rb)?(e=Lb.c(Ta,Sa(e),this),e=Ua(e)):e=Lb.c(ta,e,this):e=Lb.c(rb,N,this);return a(d(e,b,c),this.l)}return c===this.b[a+1]?this:t?(b=x(this.b),b[a+1]=c,new ia(this.l,this.e,b,null)):null};
f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return this.L(null,a)};f.a=function(a,b){return this.M(null,a,b)};f.B=function(a,b){return Eb(b)?xa(this,z.a(b,0),z.a(b,1)):Lb.c(ta,this,b)};f.toString=function(){return H(this)};
f.C=function(){var a=this.b;return 0<=a.length-2?new ed(a,0,null):null};f.F=function(){return this.e};f.t=function(a,b){return cd(this,b)};f.I=function(a,b){return new ia(b,this.e,this.b,this.j)};f.G=function(){return this.l};var id=new ia(null,0,[],null),gd=8;function fd(a,b,c){this.la=a;this.ja=b;this.b=c;this.o=56;this.f=258}f=fd.prototype;
f.ta=function(a,b,c){if(q(this.la)){a=dd(this,b);if(-1===a)return this.ja+2<=2*gd?(this.ja+=2,this.b.push(b),this.b.push(c),this):mc.c(jd.a?jd.a(this.ja,this.b):jd.call(null,this.ja,this.b),b,c);c!==this.b[a+1]&&(this.b[a+1]=c);return this}throw Error("assoc! after persistent!");};
f.xa=function(a,b){if(q(this.la)){if(b?b.f&2048||b.bb||(b.f?0:s(Aa,b)):s(Aa,b))return Va(this,Sb.d?Sb.d(b):Sb.call(null,b),Tb.d?Tb.d(b):Tb.call(null,b));for(var c=J(b),d=this;;){var e=L(c);if(q(e))c=P(c),d=Va(d,Sb.d?Sb.d(e):Sb.call(null,e),Tb.d?Tb.d(e):Tb.call(null,e));else return d}}else throw Error("conj! after persistent!");};f.ya=function(){if(q(this.la))return this.la=!1,new ia(null,Nb(this.ja),this.b,null);throw Error("persistent! called twice");};f.L=function(a,b){return C.c(this,b,null)};
f.M=function(a,b,c){if(q(this.la))return a=dd(this,b),-1===a?c:this.b[a+1];throw Error("lookup after persistent!");};f.F=function(){if(q(this.la))return Nb(this.ja);throw Error("count after persistent!");};function jd(a,b){for(var c=Sa(hd),d=0;;)if(d<a)c=mc.c(c,b[d],b[d+1]),d+=2;else return c}function kd(){this.ba=!1}function ld(a,b){return a===b?!0:a===b||a instanceof V&&b instanceof V&&a.fa===b.fa?!0:t?cb.a(a,b):null}
var md=function(){function a(a,b,c,h,k){a=x(a);a[b]=c;a[h]=k;return a}function b(a,b,c){a=x(a);a[b]=c;return a}var c=null,c=function(c,e,g,h,k){switch(arguments.length){case 3:return b.call(this,c,e,g);case 5:return a.call(this,c,e,g,h,k)}throw Error("Invalid arity: "+arguments.length);};c.c=b;c.A=a;return c}(),nd=function(){function a(a,b,c,h,k,l){a=a.ma(b);a.b[c]=h;a.b[k]=l;return a}function b(a,b,c,h){a=a.ma(b);a.b[c]=h;return a}var c=null,c=function(c,e,g,h,k,l){switch(arguments.length){case 4:return b.call(this,
c,e,g,h);case 6:return a.call(this,c,e,g,h,k,l)}throw Error("Invalid arity: "+arguments.length);};c.i=b;c.ca=a;return c}();function od(a,b,c){this.n=a;this.v=b;this.b=c}f=od.prototype;
f.X=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Qb(this.v&h-1);if(0===(this.v&h)){var l=Qb(this.v);if(2*l<this.b.length){a=this.ma(a);b=a.b;g.ba=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];l-=1;c-=1;g-=1}b[2*k]=d;b[2*k+1]=e;a.v|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=pd.X(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==
(this.v>>>d&1)&&(k[d]=null!=this.b[e]?pd.X(a,b+5,I(this.b[e]),this.b[e],this.b[e+1],g):this.b[e+1],e+=2),d+=1;else break;return new qd(a,l+1,k)}return t?(b=Array(2*(l+4)),Hb(this.b,0,b,0,2*k),b[2*k]=d,b[2*k+1]=e,Hb(this.b,2*k,b,2*(k+1),2*(l-k)),g.ba=!0,a=this.ma(a),a.b=b,a.v|=h,a):null}l=this.b[2*k];h=this.b[2*k+1];return null==l?(l=h.X(a,b+5,c,d,e,g),l===h?this:nd.i(this,a,2*k+1,l)):ld(d,l)?e===h?this:nd.i(this,a,2*k+1,e):t?(g.ba=!0,nd.ca(this,a,2*k,null,2*k+1,rd.ka?rd.ka(a,b+5,l,h,c,d,e):rd.call(null,
a,b+5,l,h,c,d,e))):null};f.ua=function(){return sd.d?sd.d(this.b):sd.call(null,this.b)};f.ma=function(a){if(a===this.n)return this;var b=Qb(this.v),c=Array(0>b?4:2*(b+1));Hb(this.b,0,c,0,2*b);return new od(a,this.v,c)};
f.W=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Qb(this.v&g-1);if(0===(this.v&g)){var k=Qb(this.v);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=pd.W(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.v>>>c&1)&&(h[c]=null!=this.b[d]?pd.W(a+5,I(this.b[d]),this.b[d],this.b[d+1],e):this.b[d+1],d+=2),c+=1;else break;return new qd(null,k+1,h)}a=Array(2*(k+1));Hb(this.b,0,a,
0,2*h);a[2*h]=c;a[2*h+1]=d;Hb(this.b,2*h,a,2*(h+1),2*(k-h));e.ba=!0;return new od(null,this.v|g,a)}k=this.b[2*h];g=this.b[2*h+1];return null==k?(k=g.W(a+5,b,c,d,e),k===g?this:new od(null,this.v,md.c(this.b,2*h+1,k))):ld(c,k)?d===g?this:new od(null,this.v,md.c(this.b,2*h+1,d)):t?(e.ba=!0,new od(null,this.v,md.A(this.b,2*h,null,2*h+1,rd.ca?rd.ca(a+5,k,g,b,c,d):rd.call(null,a+5,k,g,b,c,d)))):null};
f.ia=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.v&e))return d;var g=Qb(this.v&e-1),e=this.b[2*g],g=this.b[2*g+1];return null==e?g.ia(a+5,b,c,d):ld(c,e)?g:t?d:null};var pd=new od(null,0,[]);function qd(a,b,c){this.n=a;this.e=b;this.b=c}f=qd.prototype;f.X=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.b[h];if(null==k)return a=nd.i(this,a,h,pd.X(a,b+5,c,d,e,g)),a.e+=1,a;b=k.X(a,b+5,c,d,e,g);return b===k?this:nd.i(this,a,h,b)};f.ua=function(){return td.d?td.d(this.b):td.call(null,this.b)};
f.ma=function(a){return a===this.n?this:new qd(a,this.e,x(this.b))};f.W=function(a,b,c,d,e){var g=b>>>a&31,h=this.b[g];if(null==h)return new qd(null,this.e+1,md.c(this.b,g,pd.W(a+5,b,c,d,e)));a=h.W(a+5,b,c,d,e);return a===h?this:new qd(null,this.e,md.c(this.b,g,a))};f.ia=function(a,b,c,d){var e=this.b[b>>>a&31];return null!=e?e.ia(a+5,b,c,d):d};function ud(a,b,c){b*=2;for(var d=0;;)if(d<b){if(ld(c,a[d]))return d;d+=2}else return-1}function vd(a,b,c,d){this.n=a;this.ea=b;this.e=c;this.b=d}f=vd.prototype;
f.X=function(a,b,c,d,e,g){if(c===this.ea){b=ud(this.b,this.e,d);if(-1===b){if(this.b.length>2*this.e)return a=nd.ca(this,a,2*this.e,d,2*this.e+1,e),g.ba=!0,a.e+=1,a;c=this.b.length;b=Array(c+2);Hb(this.b,0,b,0,c);b[c]=d;b[c+1]=e;g.ba=!0;g=this.e+1;a===this.n?(this.b=b,this.e=g,a=this):a=new vd(this.n,this.ea,g,b);return a}return this.b[b+1]===e?this:nd.i(this,a,b+1,e)}return(new od(a,1<<(this.ea>>>b&31),[null,this,null,null])).X(a,b,c,d,e,g)};
f.ua=function(){return sd.d?sd.d(this.b):sd.call(null,this.b)};f.ma=function(a){if(a===this.n)return this;var b=Array(2*(this.e+1));Hb(this.b,0,b,0,2*this.e);return new vd(a,this.ea,this.e,b)};f.W=function(a,b,c,d,e){return b===this.ea?(a=ud(this.b,this.e,c),-1===a?(a=2*this.e,b=Array(a+2),Hb(this.b,0,b,0,a),b[a]=c,b[a+1]=d,e.ba=!0,new vd(null,this.ea,this.e+1,b)):cb.a(this.b[a],d)?this:new vd(null,this.ea,this.e,md.c(this.b,a+1,d))):(new od(null,1<<(this.ea>>>a&31),[null,this])).W(a,b,c,d,e)};
f.ia=function(a,b,c,d){a=ud(this.b,this.e,c);return 0>a?d:ld(c,this.b[a])?this.b[a+1]:t?d:null};
var rd=function(){function a(a,b,c,h,k,l,n){var p=I(c);if(p===k)return new vd(null,p,2,[c,h,l,n]);var r=new kd;return pd.X(a,b,p,c,h,r).X(a,b,k,l,n,r)}function b(a,b,c,h,k,l){var n=I(b);if(n===h)return new vd(null,n,2,[b,c,k,l]);var p=new kd;return pd.W(a,n,b,c,p).W(a,h,k,l,p)}var c=null,c=function(c,e,g,h,k,l,n){switch(arguments.length){case 6:return b.call(this,c,e,g,h,k,l);case 7:return a.call(this,c,e,g,h,k,l,n)}throw Error("Invalid arity: "+arguments.length);};c.ca=b;c.ka=a;return c}();
function wd(a,b,c,d,e){this.l=a;this.Y=b;this.k=c;this.p=d;this.j=e;this.o=0;this.f=32374860}f=wd.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){return this};f.P=function(){return null==this.p?new X(null,2,5,Z,[this.Y[this.k],this.Y[this.k+1]],null):L(this.p)};
f.Q=function(){return null==this.p?sd.c?sd.c(this.Y,this.k+2,null):sd.call(null,this.Y,this.k+2,null):sd.c?sd.c(this.Y,this.k,P(this.p)):sd.call(null,this.Y,this.k,P(this.p))};f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new wd(b,this.Y,this.k,this.p,this.j)};f.G=function(){return this.l};
var sd=function(){function a(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new wd(null,a,b,null,null);var h=a[b+1];if(q(h)&&(h=h.ua(),q(h)))return new wd(null,a,b+2,h,null);b+=2}else return null;else return new wd(null,a,b,c,null)}function b(a){return c.c(a,0,null)}var c=null,c=function(c,e,g){switch(arguments.length){case 1:return b.call(this,c);case 3:return a.call(this,c,e,g)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.c=a;return c}();
function xd(a,b,c,d,e){this.l=a;this.Y=b;this.k=c;this.p=d;this.j=e;this.o=0;this.f=32374860}f=xd.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};f.N=function(a,b){return U.a(b,this)};f.O=function(a,b,c){return U.c(b,c,this)};f.C=function(){return this};f.P=function(){return L(this.p)};f.Q=function(){return td.i?td.i(null,this.Y,this.k,P(this.p)):td.call(null,null,this.Y,this.k,P(this.p))};
f.t=function(a,b){return ob(this,b)};f.I=function(a,b){return new xd(b,this.Y,this.k,this.p,this.j)};f.G=function(){return this.l};
var td=function(){function a(a,b,c,h){if(null==h)for(h=b.length;;)if(c<h){var k=b[c];if(q(k)&&(k=k.ua(),q(k)))return new xd(a,b,c+1,k,null);c+=1}else return null;else return new xd(a,b,c,h,null)}function b(a){return c.i(null,a,0,null)}var c=null,c=function(c,e,g,h){switch(arguments.length){case 1:return b.call(this,c);case 4:return a.call(this,c,e,g,h)}throw Error("Invalid arity: "+arguments.length);};c.d=b;c.i=a;return c}();
function yd(a,b,c,d,e,g){this.l=a;this.e=b;this.root=c;this.R=d;this.T=e;this.j=g;this.o=8196;this.f=16123663}f=yd.prototype;f.ra=function(){return new zd({},this.root,this.e,this.R,this.T)};f.w=function(){var a=this.j;return null!=a?a:this.j=a=Rb(this)};f.L=function(a,b){return C.c(this,b,null)};f.M=function(a,b,c){return null==b?this.R?this.T:c:null==this.root?c:t?this.root.ia(0,I(b),b,c):null};
f.qa=function(a,b,c){if(null==b)return this.R&&c===this.T?this:new yd(this.l,this.R?this.e:this.e+1,this.root,!0,c,null);a=new kd;b=(null==this.root?pd:this.root).W(0,I(b),b,c,a);return b===this.root?this:new yd(this.l,a.ba?this.e+1:this.e,b,this.R,this.T,null)};f.call=function(){var a=null;return a=function(a,c,d){switch(arguments.length){case 2:return this.L(null,c);case 3:return this.M(null,c,d)}throw Error("Invalid arity: "+arguments.length);}}();
f.apply=function(a,b){return this.call.apply(this,[this].concat(x(b)))};f.d=function(a){return this.L(null,a)};f.a=function(a,b){return this.M(null,a,b)};f.B=function(a,b){return Eb(b)?xa(this,z.a(b,0),z.a(b,1)):Lb.c(ta,this,b)};f.toString=function(){return H(this)};f.C=function(){if(0<this.e){var a=null!=this.root?this.root.ua():null;return this.R?S(new X(null,2,5,Z,[null,this.T],null),a):a}return null};f.F=function(){return this.e};f.t=function(a,b){return cd(this,b)};
f.I=function(a,b){return new yd(b,this.e,this.root,this.R,this.T,this.j)};f.G=function(){return this.l};var hd=new yd(null,0,null,!1,null,0);function vb(a,b){for(var c=a.length,d=0,e=Sa(hd);;)if(d<c)var g=d+1,e=e.ta(null,a[d],b[d]),d=g;else return Ua(e)}function zd(a,b,c,d,e){this.n=a;this.root=b;this.count=c;this.R=d;this.T=e;this.o=56;this.f=258}f=zd.prototype;f.ta=function(a,b,c){return Ad(this,b,c)};
f.xa=function(a,b){var c;a:{if(this.n){if(b?b.f&2048||b.bb||(b.f?0:s(Aa,b)):s(Aa,b)){c=Ad(this,Sb.d?Sb.d(b):Sb.call(null,b),Tb.d?Tb.d(b):Tb.call(null,b));break a}c=J(b);for(var d=this;;){var e=L(c);if(q(e))c=P(c),d=Ad(d,Sb.d?Sb.d(e):Sb.call(null,e),Tb.d?Tb.d(e):Tb.call(null,e));else{c=d;break a}}}else throw Error("conj! after persistent");c=void 0}return c};
f.ya=function(){var a;if(this.n)this.n=null,a=new yd(null,this.count,this.root,this.R,this.T,null);else throw Error("persistent! called twice");return a};f.L=function(a,b){return null==b?this.R?this.T:null:null==this.root?null:this.root.ia(0,I(b),b)};f.M=function(a,b,c){return null==b?this.R?this.T:c:null==this.root?c:this.root.ia(0,I(b),b,c)};f.F=function(){if(this.n)return this.count;throw Error("count after persistent!");};
function Ad(a,b,c){if(a.n){if(null==b)a.T!==c&&(a.T=c),a.R||(a.count+=1,a.R=!0);else{var d=new kd;b=(null==a.root?pd:a.root).X(a.n,0,I(b),b,c,d);b!==a.root&&(a.root=b);d.ba&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}
var Bd=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){a=J(a);for(var b=Sa(hd);;)if(a){var e=P(P(a)),b=mc.c(b,L(a),L(P(a)));a=e}else return Ua(b)}a.m=0;a.h=function(a){a=J(a);return b(a)};a.g=b;return a}();function Sb(a){return Ba(a)}function Tb(a){return Ca(a)}function Yb(a){if(a&&(a.o&4096||a.eb))return a.name;if("string"===typeof a)return a;throw Error([w("Doesn't support name: "),w(a)].join(""));}
function Cd(a,b,c,d,e){this.l=a;this.start=b;this.end=c;this.step=d;this.j=e;this.f=32375006;this.o=8192}f=Cd.prototype;f.w=function(){var a=this.j;return null!=a?a:this.j=a=nb(this)};f.Z=function(){return 0<this.step?this.start+this.step<this.end?new Cd(this.l,this.start+this.step,this.end,this.step,null):null:this.start+this.step>this.end?new Cd(this.l,this.start+this.step,this.end,this.step,null):null};f.B=function(a,b){return S(b,this)};f.toString=function(){return H(this)};
f.N=function(a,b){return jb.a(this,b)};f.O=function(a,b,c){return jb.c(this,b,c)};f.C=function(){return 0<this.step?this.start<this.end?this:null:this.start>this.end?this:null};f.F=function(){return oa(Na(this))?0:Math.ceil((this.end-this.start)/this.step)};f.P=function(){return null==Na(this)?null:this.start};f.Q=function(){return null!=Na(this)?new Cd(this.l,this.start+this.step,this.end,this.step,null):N};f.t=function(a,b){return ob(this,b)};
f.I=function(a,b){return new Cd(b,this.start,this.end,this.step,this.j)};f.G=function(){return this.l};f.K=function(a,b){if(b<y(this))return this.start+b*this.step;if(this.start>this.end&&0===this.step)return this.start;throw Error("Index out of bounds");};f.S=function(a,b,c){return b<y(this)?this.start+b*this.step:this.start>this.end&&0===this.step?this.start:c};
var Dd=function(){function a(a,b,c){return new Cd(null,a,b,c,null)}function b(a,b){return e.c(a,b,1)}function c(a){return e.c(0,a,1)}function d(){return e.c(0,Number.MAX_VALUE,1)}var e=null,e=function(e,h,k){switch(arguments.length){case 0:return d.call(this);case 1:return c.call(this,e);case 2:return b.call(this,e,h);case 3:return a.call(this,e,h,k)}throw Error("Invalid arity: "+arguments.length);};e.s=d;e.d=c;e.a=b;e.c=a;return e}();
function Ed(a,b,c,d,e,g,h){var k=fa;try{fa=null==fa?null:fa-1;if(null!=fa&&0>fa)return G(a,"#");G(a,c);J(h)&&(b.c?b.c(L(h),a,g):b.call(null,L(h),a,g));for(var l=P(h),n=na.d(g);l&&(null==n||0!==n);){G(a,d);b.c?b.c(L(l),a,g):b.call(null,L(l),a,g);var p=P(l);c=n-1;l=p;n=c}q(na.d(g))&&(G(a,d),b.c?b.c("...",a,g):b.call(null,"...",a,g));return G(a,e)}finally{fa=k}}
var Fd=function(){function a(a,d){var e=null;1<arguments.length&&(e=Q(Array.prototype.slice.call(arguments,1),0));return b.call(this,a,e)}function b(a,b){for(var e=J(b),g=null,h=0,k=0;;)if(k<h){var l=g.K(null,k);G(a,l);k+=1}else if(e=J(e))g=e,Fb(g)?(e=Ya(g),h=Za(g),g=e,l=T(e),e=h,h=l):(l=L(g),G(a,l),e=P(g),g=null,h=0),k=0;else return null}a.m=1;a.h=function(a){var d=L(a);a=M(a);return b(d,a)};a.g=b;return a}(),Gd={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};
function Hd(a){return[w('"'),w(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return Gd[a]})),w('"')].join("")}
var $=function Id(b,c,d){if(null==b)return G(c,"nil");if(void 0===b)return G(c,"#\x3cundefined\x3e");if(t){q(function(){var c=ub.a(d,la);return q(c)?(c=b?b.f&131072||b.cb?!0:b.f?!1:s(Fa,b):s(Fa,b))?yb(b):c:c}())&&(G(c,"^"),Id(yb(b),c,d),G(c," "));if(null==b)return G(c,"nil");if(b.mb)return b.yb(c);if(b&&(b.f&2147483648||b.H))return b.u(null,c,d);if(pa(b)===Boolean||"number"===typeof b)return G(c,""+w(b));if(null!=b&&b.constructor===Object)return G(c,"#js "),Jd.i?Jd.i(tc.a(function(c){return new X(null,
2,5,Z,[Zb.d(c),b[c]],null)},Gb(b)),Id,c,d):Jd.call(null,tc.a(function(c){return new X(null,2,5,Z,[Zb.d(c),b[c]],null)},Gb(b)),Id,c,d);if(b instanceof Array)return Ed(c,Id,"#js ["," ","]",d,b);if("string"==typeof b)return q(ka.d(d))?G(c,Hd(b)):G(c,b);if(xb(b))return Fd.g(c,Q(["#\x3c",""+w(b),"\x3e"],0));if(b instanceof Date){var e=function(b,c){for(var d=""+w(b);;)if(T(d)<c)d=[w("0"),w(d)].join("");else return d};return Fd.g(c,Q(['#inst "',""+w(b.getUTCFullYear()),"-",e(b.getUTCMonth()+1,2),"-",e(b.getUTCDate(),
2),"T",e(b.getUTCHours(),2),":",e(b.getUTCMinutes(),2),":",e(b.getUTCSeconds(),2),".",e(b.getUTCMilliseconds(),3),"-",'00:00"'],0))}return b instanceof RegExp?Fd.g(c,Q(['#"',b.source,'"'],0)):(b?b.f&2147483648||b.H||(b.f?0:s(Pa,b)):s(Pa,b))?Qa(b,c,d):t?Fd.g(c,Q(["#\x3c",""+w(b),"\x3e"],0)):null}return null},Kd=function(){function a(a){var d=null;0<arguments.length&&(d=Q(Array.prototype.slice.call(arguments,0),0));return b.call(this,d)}function b(a){var b=ha();if(null==a||oa(J(a)))b="";else{var e=
w,g=new ea;a:{var h=new ab(g);$(L(a),h,b);a=J(P(a));for(var k=null,l=0,n=0;;)if(n<l){var p=k.K(null,n);G(h," ");$(p,h,b);n+=1}else if(a=J(a))k=a,Fb(k)?(a=Ya(k),l=Za(k),k=a,p=T(a),a=l,l=p):(p=L(k),G(h," "),$(p,h,b),a=P(k),k=null,l=0),n=0;else break a}b=""+e(g)}return b}a.m=0;a.h=function(a){a=J(a);return b(a)};a.g=b;return a}();function Jd(a,b,c,d){return Ed(c,function(a,c,d){b.c?b.c(Ba(a),c,d):b.call(null,Ba(a),c,d);G(c," ");return b.c?b.c(Ca(a),c,d):b.call(null,Ca(a),c,d)},"{",", ","}",d,J(a))}
hb.prototype.H=!0;hb.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};Wc.prototype.H=!0;Wc.prototype.u=function(a,b,c){return Ed(b,$,"["," ","]",c,this)};dc.prototype.H=!0;dc.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};ia.prototype.H=!0;ia.prototype.u=function(a,b,c){return Jd(this,$,b,c)};W.prototype.H=!0;W.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};wd.prototype.H=!0;wd.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};
Uc.prototype.H=!0;Uc.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};yd.prototype.H=!0;yd.prototype.u=function(a,b,c){return Jd(this,$,b,c)};X.prototype.H=!0;X.prototype.u=function(a,b,c){return Ed(b,$,"["," ","]",c,this)};Ub.prototype.H=!0;Ub.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};ed.prototype.H=!0;ed.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};Vb.prototype.H=!0;Vb.prototype.u=function(a,b){return G(b,"()")};Xb.prototype.H=!0;
Xb.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};Cd.prototype.H=!0;Cd.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};xd.prototype.H=!0;xd.prototype.u=function(a,b,c){return Ed(b,$,"("," ",")",c,this)};X.prototype.va=!0;X.prototype.wa=function(a,b){return Kb.a(this,b)};Wc.prototype.va=!0;Wc.prototype.wa=function(a,b){return Kb.a(this,b)};V.prototype.va=!0;V.prototype.wa=function(a,b){return bb(this,b)};fb.prototype.va=!0;
fb.prototype.wa=function(a,b){return bb(this,b)};function Ld(a,b){if(a?a.gb:a)return a.gb(a,b);var c;c=Ld[m(null==a?null:a)];if(!c&&(c=Ld._,!c))throw v("IReset.-reset!",a);return c.call(null,a,b)}
var Md=function(){function a(a,b,c,d,e){if(a?a.kb:a)return a.kb(a,b,c,d,e);var p;p=Md[m(null==a?null:a)];if(!p&&(p=Md._,!p))throw v("ISwap.-swap!",a);return p.call(null,a,b,c,d,e)}function b(a,b,c,d){if(a?a.jb:a)return a.jb(a,b,c,d);var e;e=Md[m(null==a?null:a)];if(!e&&(e=Md._,!e))throw v("ISwap.-swap!",a);return e.call(null,a,b,c,d)}function c(a,b,c){if(a?a.ib:a)return a.ib(a,b,c);var d;d=Md[m(null==a?null:a)];if(!d&&(d=Md._,!d))throw v("ISwap.-swap!",a);return d.call(null,a,b,c)}function d(a,b){if(a?
a.hb:a)return a.hb(a,b);var c;c=Md[m(null==a?null:a)];if(!c&&(c=Md._,!c))throw v("ISwap.-swap!",a);return c.call(null,a,b)}var e=null,e=function(e,h,k,l,n){switch(arguments.length){case 2:return d.call(this,e,h);case 3:return c.call(this,e,h,k);case 4:return b.call(this,e,h,k,l);case 5:return a.call(this,e,h,k,l,n)}throw Error("Invalid arity: "+arguments.length);};e.a=d;e.c=c;e.i=b;e.A=a;return e}();function Nd(a,b,c,d){this.state=a;this.l=b;this.ob=c;this.Za=d;this.f=2153938944;this.o=16386}f=Nd.prototype;
f.w=function(){return this[aa]||(this[aa]=++ba)};f.Xa=function(a,b,c){a=J(this.Za);for(var d=null,e=0,g=0;;)if(g<e){var h=d.K(null,g),k=tb.c(h,0,null),h=tb.c(h,1,null);h.i?h.i(k,this,b,c):h.call(null,k,this,b,c);g+=1}else if(a=J(a))Fb(a)?(d=Ya(a),a=Za(a),k=d,e=T(d),d=k):(d=L(a),k=tb.c(d,0,null),h=tb.c(d,1,null),h.i?h.i(k,this,b,c):h.call(null,k,this,b,c),a=P(a),d=null,e=0),g=0;else return null};f.u=function(a,b,c){G(b,"#\x3cAtom: ");$(this.state,b,c);return G(b,"\x3e")};f.G=function(){return this.l};
f.ab=function(){return this.state};f.t=function(a,b){return this===b};
var Pd=function(){function a(a){return new Nd(a,null,null,null)}var b=null,c=function(){function a(c,d){var k=null;1<arguments.length&&(k=Q(Array.prototype.slice.call(arguments,1),0));return b.call(this,c,k)}function b(a,c){var d=(null==c?0:c?c.f&64||c.sa||(c.f?0:s(va,c)):s(va,c))?oc.a(Bd,c):c,e=ub.a(d,Od),d=ub.a(d,la);return new Nd(a,d,e,null)}a.m=1;a.h=function(a){var c=L(a);a=M(a);return b(c,a)};a.g=b;return a}(),b=function(b,e){switch(arguments.length){case 1:return a.call(this,b);default:return c.g(b,
Q(arguments,1))}throw Error("Invalid arity: "+arguments.length);};b.m=1;b.h=c.h;b.d=a;b.g=c.g;return b}();function Qd(a,b){if(a instanceof Nd){var c=a.ob;if(null!=c&&!q(c.d?c.d(b):c.call(null,b)))throw Error([w("Assert failed: "),w("Validator rejected reference state"),w("\n"),w(Kd.g(Q([Wb(new fb(null,"validate","validate",1233162959,null),new fb(null,"new-value","new-value",972165309,null))],0)))].join(""));c=a.state;a.state=b;null!=a.Za&&Ra(a,c,b);return b}return Ld(a,b)}
var Rd=function(){function a(a,b,c,d){return a instanceof Nd?Qd(a,b.c?b.c(a.state,c,d):b.call(null,a.state,c,d)):Md.i(a,b,c,d)}function b(a,b,c){return a instanceof Nd?Qd(a,b.a?b.a(a.state,c):b.call(null,a.state,c)):Md.c(a,b,c)}function c(a,b){return a instanceof Nd?Qd(a,b.d?b.d(a.state):b.call(null,a.state)):Md.a(a,b)}var d=null,e=function(){function a(c,d,e,g,r){var u=null;4<arguments.length&&(u=Q(Array.prototype.slice.call(arguments,4),0));return b.call(this,c,d,e,g,u)}function b(a,c,d,e,g){return a instanceof
Nd?Qd(a,oc.A(c,a.state,d,e,g)):Md.A(a,c,d,e,g)}a.m=4;a.h=function(a){var c=L(a);a=P(a);var d=L(a);a=P(a);var e=L(a);a=P(a);var g=L(a);a=M(a);return b(c,d,e,g,a)};a.g=b;return a}(),d=function(d,h,k,l,n){switch(arguments.length){case 2:return c.call(this,d,h);case 3:return b.call(this,d,h,k);case 4:return a.call(this,d,h,k,l);default:return e.g(d,h,k,l,Q(arguments,4))}throw Error("Invalid arity: "+arguments.length);};d.m=4;d.h=e.h;d.a=c;d.c=b;d.i=a;d.g=e.g;return d}(),Ob=function(){function a(a){return(Math.random.s?
Math.random.s():Math.random.call(null))*a}function b(){return c.d(1)}var c=null,c=function(c){switch(arguments.length){case 0:return b.call(this);case 1:return a.call(this,c)}throw Error("Invalid arity: "+arguments.length);};c.s=b;c.d=a;return c}(),Pb=function(a){return Math.floor.d?Math.floor.d((Math.random.s?Math.random.s():Math.random.call(null))*a):Math.floor.call(null,(Math.random.s?Math.random.s():Math.random.call(null))*a)};function Sd(a){return tb.a(a,Pb(T(a)))};var Td=Pd.d(id),Ud=Pd.d(0),Vd=Pd.d(Rc),Wd=Pd.d(0);Pd.d(0);var Xd=Pd.d(id),Yd=Pd.d(id);function Zd(){F(Xd).width=window.innerWidth;F(Xd).height=window.innerHeight}function $d(a){a:{var b=Dd.d(a),c=wc.a(a,id);a=Sa(id);b=J(b);for(c=J(c);;)if(b&&c)a=mc.c(a,L(b),L(c)),b=P(b),c=P(c);else{a=Ua(a);break a}a=void 0}return a}function ae(a){return zc.a(F(Td),a)}function be(a){return"string"===typeof ae(a)}function ce(a){return"string"!==typeof ae(a)}
function de(){for(var a=T(F(Td)),b=0;;)if(b<a){for(var c=T(F(Td)),d=0;;)if(d<c)be(new X(null,2,5,Z,[b,d],null))?F(Yd).fillStyle="navy":F(Yd).fillStyle="grey",F(Yd).fillRect(10*d,10*b,10,10),d+=1;else break;b+=1}else return null}function ee(a){return oc.a(Tc,tc.a(function(b){return new X(null,2,5,Z,[L(a)+L(b),qb(a)+qb(b)],null)},new X(null,4,5,Z,[new X(null,2,5,Z,[-1,0],null),new X(null,2,5,Z,[1,0],null),new X(null,2,5,Z,[0,-1],null),new X(null,2,5,Z,[0,1],null)],null)))}
function fe(a,b){var c=L(b)-L(a),d=qb(b)-qb(a);return new X(null,2,5,Z,[L(b)+c,qb(b)+d],null)}function ge(a){return 0<L(a)&&0<qb(a)&&L(a)<F(Ud)&&qb(a)<F(Ud)}function he(){var a=F(Vd),b=Pb(T(a)),c=ub.a(a,b),d=Sd(oc.a(Tc,yc(be,ee(c)))),e=fe(d,c),a=oc.a(Tc,rc(function(a){return function(b,c){return cb.a(b,a)?null:c}}(b,c,d,e),a));return ge(e)&&ce(e)?(Rd.i(Td,Bc,c,"wut"),Rd.i(Td,Bc,e,"wut"),oc.c(Tc,jc.d(a),oc.a(Tc,yc(ce,ee(e))))):a}
var je=function ie(){Rd.a(Wd,ib);var b=Math.round((new Date).getTime());if(0<T(F(Vd))){var c=he();de();var d=document.getElementById("frame-number"),e=document.getElementById("wall-count");document.getElementById("frame-time").innerHTML=Math.round((new Date).getTime())-b;e.innerHTML=T(F(Vd));d.innerHTML=F(Wd);Qd(Vd,c);return setTimeout(ie,1E3)}return null};
function ke(){Qd(Xd,document.getElementById("display"));Qd(Yd,F(Xd).getContext("2d"));Zd();window.onresize=function(){Zd();return de()};var a=Math.floor(window.innerHeight/10),b=Math.floor(a/2),b=new X(null,2,5,Z,[b,b],null);Qd(Ud,a);Qd(Td,$d(a));Rd.i(Td,Bc,b,"start");Qd(Vd,oc.a(Tc,yc(ce,ee(b))));return je()}var le=["maze","start"],me=this;le[0]in me||!me.execScript||me.execScript("var "+le[0]);for(var ne;le.length&&(ne=le.shift());)le.length||void 0===ke?me=me[ne]?me[ne]:me[ne]={}:me[ne]=ke;var ma=new V(null,"dup","dup"),eb=new V(null,"default","default"),ja=new V(null,"flush-on-newline","flush-on-newline"),na=new V(null,"print-length","print-length"),t=new V(null,"else","else"),ka=new V(null,"readably","readably"),Od=new V(null,"validator","validator"),la=new V(null,"meta","meta");
